version: "3.9"

services:
  # ── Backend Service ───────────────────────────────────────────────────────────
  authentication-service:
    container_name: authentication-service
    build:
      dockerfile: Dockerfile
    ports:
      - "26022:26022"
    networks:
      - cm-network
    restart: always

networks:
  cm-network:
    driver: bridge
