version: '3.9'

services:
  redis:
    image: redis:7.0.11
    container_name: redis-server
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - cm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 300M
        reservations:
          cpus: '0.30'
          memory: 50M
networks:
  cm-network:
    external: true

volumes:
  redis-data: