-- Dummy data for the Features page (Loyverse-style: Sell / Manage / Grow)
INSERT INTO public.features (id, title, title_kh, description, description_kh, category, category_kh, icon, link, sort_order) VALUES
  -- ── Sell ──────────────────────────────────────────────────────────────────
  (gen_random_uuid()::text,
   'Point of Sale',
   'ប្រព័ន្ធគ្រប់គ្រងការលក់',
   'Turn your smartphone or tablet into a powerful point of sale. Ring up sales, apply discounts, and accept multiple payment types — even while offline.',
   'ប្រែក្លាយស្មាតហ្វូន ឬថេប្លេតរបស់អ្នកទៅជាប្រព័ន្ធលក់ដ៏មានឥទ្ធិភាព។ គិតលុយ បញ្ចុះតម្លៃ និងទទួលការទូទាត់ច្រើនប្រភេទ — ទោះបីគ្មានអ៊ីនធឺណិតក៏ដោយ។',
   'Sell', 'លក់', 'shopping-cart', NULL, 1),
  (gen_random_uuid()::text,
   'Payments',
   'ការទូទាត់',
   'Accept cash, cards, QR codes, and mobile wallets. Split payments across multiple methods and issue refunds in seconds.',
   'ទទួលសាច់ប្រាក់ កាត QR កូដ និងកាបូបចល័ត។ បំបែកការទូទាត់តាមវិធីច្រើន និងបង្វិលប្រាក់វិញក្នុងរយៈពេលប៉ុន្មានវិនាទី។',
   'Sell', 'លក់', 'credit-card', NULL, 2),
  (gen_random_uuid()::text,
   'Receipts',
   'បង្កាន់ដៃ',
   'Send digital receipts by email or print them instantly. Customize your receipt with your logo and promotional messages.',
   'ផ្ញើបង្កាន់ដៃឌីជីថលតាមអ៊ីមែល ឬបោះពុម្ពភ្លាមៗ។ កែសម្រួលបង្កាន់ដៃជាមួយឡូហ្គោ និងសារផ្សព្វផ្សាយរបស់អ្នក។',
   'Sell', 'លក់', 'receipt', NULL, 3),

  -- ── Manage ────────────────────────────────────────────────────────────────
  (gen_random_uuid()::text,
   'Inventory Management',
   'គ្រប់គ្រងស្តុកទំនិញ',
   'Track stock levels in real time, receive low-stock alerts, and manage purchase orders across all your stores from one place.',
   'តាមដានកម្រិតស្តុកជាក់ស្តែង ទទួលការជូនដំណឹងពេលស្តុកជិតអស់ និងគ្រប់គ្រងការបញ្ជាទិញនៅគ្រប់ហាងរបស់អ្នកពីកន្លែងតែមួយ។',
   'Manage', 'គ្រប់គ្រង', 'package', NULL, 10),
  (gen_random_uuid()::text,
   'Sales Analytics',
   'ការវិភាគការលក់',
   'Understand your business with real-time reports on revenue, best-selling items, and employee performance.',
   'យល់ដឹងពីអាជីវកម្មរបស់អ្នកជាមួយរបាយការណ៍ជាក់ស្តែងអំពីចំណូល ទំនិញលក់ដាច់បំផុត និងសមត្ថភាពបុគ្គលិក។',
   'Manage', 'គ្រប់គ្រង', 'line-chart', NULL, 11),
  (gen_random_uuid()::text,
   'Multi-Store',
   'ហាងច្រើនសាខា',
   'Manage multiple locations under one account. Compare performance, transfer stock, and set store-specific prices.',
   'គ្រប់គ្រងទីតាំងច្រើនក្នុងគណនីតែមួយ។ ប្រៀបធៀបលទ្ធផល ផ្ទេរស្តុក និងកំណត់តម្លៃតាមសាខានីមួយៗ។',
   'Manage', 'គ្រប់គ្រង', 'store', NULL, 12),

  -- ── Grow ──────────────────────────────────────────────────────────────────
  (gen_random_uuid()::text,
   'Customer Loyalty',
   'កម្មវិធីភក្តីភាពអតិថិជន',
   'Reward repeat customers with a built-in loyalty program. Track points, offer bonuses, and keep customers coming back.',
   'ផ្តល់រង្វាន់ដល់អតិថិជនប្រចាំជាមួយកម្មវិធីភក្តីភាព។ តាមដានពិន្ទុ ផ្តល់ប្រាក់រង្វាន់ និងធ្វើឱ្យអតិថិជនត្រឡប់មកវិញ។',
   'Grow', 'រីកចម្រើន', 'gift', NULL, 20),
  (gen_random_uuid()::text,
   'Customer Management',
   'គ្រប់គ្រងអតិថិជន',
   'Build your customer base and see purchase history at a glance. Add notes and personalize every interaction.',
   'បង្កើតមូលដ្ឋានអតិថិជន និងមើលប្រវត្តិការទិញភ្លាមៗ។ បន្ថែមកំណត់ចំណាំ និងធ្វើទំនាក់ទំនងផ្ទាល់ខ្លួន។',
   'Grow', 'រីកចម្រើន', 'users', NULL, 21),
  (gen_random_uuid()::text,
   '24/7 Support',
   'ជំនួយ 24/7',
   'Get help whenever you need it with our around-the-clock customer support team, in Khmer and English.',
   'ទទួលជំនួយគ្រប់ពេលដែលអ្នកត្រូវការ ជាមួយក្រុមជំនួយអតិថិជន 24 ម៉ោង ជាភាសាខ្មែរ និងអង់គ្លេស។',
   'Grow', 'រីកចម្រើន', 'headphones', NULL, 22);
